import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'

export async function POST(request: Request) {
    try {
        const { data } = await request.json()

        if (!data || !data.nodes || !data.edges) {
            return NextResponse.json({ error: 'Missing nodes or edges data' }, { status: 400 })
        }

        const supabase = createAdminClient()
        const datasetId = crypto.randomUUID()
        const scenarioId = crypto.randomUUID()
        const datasetName = `${data.companyName || 'AI Generated'} - ${new Date().toLocaleDateString()}`

        // 1. Create Dataset record
        const { error: dsErr } = await supabase
            .from('datasets')
            .insert({
                id: datasetId,
                name: datasetName,
                upload_type: 'ai_generated',
                status: 'active',
                uploaded_at: new Date().toISOString(),
                metadata: {
                    source: 'ai_advisor',
                    companyName: data.companyName,
                    cargo: data.cargo,
                    summary: data.summary,
                    recommendations: data.recommendations,
                    generatedAt: new Date().toISOString()
                }
            })

        if (dsErr) throw new Error(`Failed to create dataset: ${dsErr.message}`)

        // 2. Insert Nodes
        const nodeRecords = data.nodes.map((n: any) => ({
            id: n.id.startsWith('node_') ? `${datasetId}_${n.id}` : n.id,
            dataset_id: datasetId,
            name: n.name,
            type: n.type || 'HUB',
            latitude: n.latitude,
            longitude: n.longitude,
            metadata: {
                city: n.city,
                country: n.country,
                source: 'ai_generated'
            }
        }))

        const { error: nodesErr } = await supabase
            .from('logistics_nodes')
            .insert(nodeRecords)

        if (nodesErr) throw new Error(`Failed to insert nodes: ${nodesErr.message}`)

        // 3. Insert Edges
        const edgeRecords = data.edges.map((e: any, idx: number) => {
            const sourceId = e.source.startsWith('node_') ? `${datasetId}_${e.source}` : e.source
            const targetId = e.target.startsWith('node_') ? `${datasetId}_${e.target}` : e.target
            return {
                id: `${datasetId}_edge_${idx}`,
                dataset_id: datasetId,
                source_node_id: sourceId,
                target_node_id: targetId,
                mode: e.mode || 'truck',
                distance: e.distance || 0,
                base_cost_usd: e.cost_per_unit || 0,
                capacity: e.capacity,
                metadata: { source: 'ai_generated' }
            }
        })

        const { error: edgesErr } = await supabase
            .from('route_edges')
            .insert(edgeRecords)

        if (edgesErr) throw new Error(`Failed to insert edges: ${edgesErr.message}`)

        // 4. Create a Scenario linked to this dataset
        const { error: scErr } = await supabase
            .from('scenarios')
            .insert({
                id: scenarioId,
                dataset_id: datasetId,
                name: `${data.companyName || 'AI'} - Base Scenario`,
                description: data.summary || 'Generated by AI Advisor',
                config: {},
                metadata: { source: 'ai_advisor' }
            })

        if (scErr) throw new Error(`Failed to create scenario: ${scErr.message}`)

        return NextResponse.json({
            datasetId,
            scenarioId,
            datasetName,
            nodesCount: nodeRecords.length,
            edgesCount: edgeRecords.length
        })
    } catch (error: any) {
        console.error('[AI Advisor Save] Error:', error)
        return NextResponse.json({ error: error.message }, { status: 500 })
    }
}
